CREATE DATABASE `weibo` /*!40100 DEFAULT CHARACTER SET utf8*/;
use weibo;
CREATE TABLE `weibo_user` (
  `id` varchar(100) NOT NULL COMMENT 'weibo id',
  `screen_name` varchar(100) DEFAULT NULL COMMENT 'screen_name',
  `name` varchar(45) DEFAULT NULL,
  `province` int(11) DEFAULT NULL,
  `city` int(11) DEFAULT NULL,
  `location` varchar(100) DEFAULT NULL,
  `description` varchar(400) DEFAULT NULL,
  `url` varchar(400) DEFAULT NULL,
  `profile_image_url` varchar(400) DEFAULT NULL,
  `user_domain` varchar(400) DEFAULT NULL,
  `gender` char(1) DEFAULT NULL,
  `followers_count` int(11) DEFAULT NULL,
  `friends_count` int(11) DEFAULT NULL,
  `statuses_count` int(11) DEFAULT '0',
  `favourites_count` int(11) DEFAULT '0',
  `created_at` varchar(400) DEFAULT NULL,
  `following` int(1) DEFAULT NULL,
  `verified` int(1) DEFAULT NULL,
  `verified_type` int(11) DEFAULT NULL,
  `allow_all_act_msg` int(1) DEFAULT NULL,
  `allow_all_comment` int(1) DEFAULT NULL,
  `follow_me` int(1) DEFAULT NULL,
  `avatar_large` varchar(400) DEFAULT NULL,
  `online_status` int(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `bi_followers_count` int(11) DEFAULT NULL,
  `remark` varchar(1000) DEFAULT NULL,
  `lang` varchar(100) DEFAULT NULL,
  `verified_reason` varchar(400) DEFAULT NULL,
  `weihao` varchar(400) DEFAULT NULL,
  `status_id` varchar(400) DEFAULT NULL,
  `insert_date` datetime DEFAULT NULL COMMENT 'data collected date and time',
  `crawl_level` int(11) DEFAULT '0',
  `crawled` int(1) DEFAULT '0',
  `uid` varchar(100) DEFAULT NULL COMMENT 'user-id',
  `blog_url` varchar(100) DEFAULT NULL COMMENT 'blog_url\nIt can be NULL.\nHowever, everyone has homepage as\n"http://www.weibo.com/u/" + id',
  `etc1` varchar(45) DEFAULT NULL COMMENT 'for later use',
  `etc2` varchar(45) DEFAULT NULL COMMENT 'for later use',
  `etc3` varchar(45) DEFAULT NULL COMMENT 'for later use',
  `id_score` int(3) DEFAULT '-1' COMMENT 'id score',
  `request_id1` varchar(45) DEFAULT NULL COMMENT 'request_id for blog',
  `request_id2` varchar(45) DEFAULT NULL COMMENT 'request_id for homepage',
  `url_score1` int(3) DEFAULT '-1' COMMENT 'score for blog',
  `url_score2` int(3) DEFAULT '-1' COMMENT 'score for homepage',
  PRIMARY KEY (`id`),
  KEY `IND_URL` (`blog_url`),
  KEY `IND_DATE` (`insert_date`),
  KEY `IND_IDSC` (`id_score`),
  KEY `IND_BGSC` (`url_score1`),
  KEY `IND_HPSC` (`url_score2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `weibo_connection` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `screen_name_a` varchar(100) DEFAULT NULL,
  `screen_name_b` varchar(100) DEFAULT NULL,
  `relation` tinyint(4) DEFAULT '0' COMMENT '0: b is friend of  b\n1: b is follwer of a',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `weibo_comment` (
  `id` varchar(100) NOT NULL COMMENT 'weibo id',
  `created_at` varchar(100) NOT NULL,
  `text` varchar(1000) DEFAULT NULL COMMENT 'comment',
  `comment_type` varchar(1) DEFAULT NULL COMMENT 'S:Status\nC:Comment',
  `comment_id` varchar(45) DEFAULT NULL COMMENT 'comment id',
  `etc1` varchar(45) DEFAULT NULL COMMENT 'for later use',
  `etc2` varchar(45) DEFAULT NULL COMMENT 'for later use',
  `etc3` varchar(45) DEFAULT NULL COMMENT 'for later use',
  `insert_date` datetime NOT NULL COMMENT 'data collected date and time',
  `blob_score` int(3) DEFAULT '-1' COMMENT 'score for blob',
  PRIMARY KEY (`created_at`,`id`,`insert_date`),
  KEY `IND_IND` (`insert_date`),
  KEY `FK_ID_idx` (`id`),
  KEY `IND_TYP` (`comment_type`),
  KEY `IND_BLCR` (`blob_score`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


